#' RGB to Grayscale
#'
#' Converts an image in RGB to the Grayscale.
#'
#' @param object Model or layer object
#' @param name An optional name string for the layer. Should be unique in a
#' model (do not reuse the same name twice). It will be autogenerated if it
#' isn't provided.
#'
#' @examples
#' \dontrun{
#' rgb_images <- layer_input(c(200, 200, 3))
#' gs_images <- layer_rgb_to_grayscale(rgb_images)
#' }
#'
#' @family image
#'
#' @export
layer_rgb_to_grayscale <- function (object, name = NULL) {

  create_layer(RGBToGrayscale, object, list(
    name = name,
    trainable = FALSE
  ))

}

RGBToGrayscale <- R6::R6Class(
  "RGBToGrayscale",
  inherit = keras::KerasLayer,
  public = list(

    initialize = function () {

    },

    call = function (x, mask = NULL) {
      tf$image$rgb_to_grayscale(x, name = "RGBToGrayscale")
    },

    compute_output_shape = function (input_shape) {
      c(input_shape[[1]], input_shape[[2]], 1L)
    }

  )

)
